# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{completeness-fu}
  s.version = "0.6.0"
  s.date = %q{2011-03-29}

  s.summary     = %q{Simple dsl for defining how to calculate how complete a model instance is (similar to LinkedIn profile completeness)}
  s.description = s.summary
  s.homepage    = %q{http://github.com/joshk/completeness-fu}

  s.authors = ["Josh Kalderimis"]
  s.email   = %q{josh.kalderimis@gmail.com}

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=

  s.extra_rdoc_files = ["readme.markdown"]
  s.rdoc_options = ["--charset=UTF-8"]
  s.rubygems_version = %q{1.3.6}

  s.require_paths = ['lib']
  s.files = `git ls-files`.split("\n")
  s.test_files  = `git ls-files -- {test,spec,features}/*`.split("\n")
  s.executables = `git ls-files -- bin/*`.split("\n").map{ |f| File.basename(f) }

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_dependency(%q<activemodel>,         ["~> 3.0"])
      s.add_development_dependency(%q<rake>,    "~> 12.3.3")
      s.add_development_dependency(%q<shoulda>, ["~> 2.11.3"])
      s.add_development_dependency(%q<mocha>,   ["~> 0.9.8"])
    else
      s.add_dependency(%q<activemodel>, ["~> 3.0"])
      s.add_dependency(%q<rake>,        "~> 12.3.3")
      s.add_dependency(%q<shoulda>,     ["~> 2.11.3"])
      s.add_dependency(%q<mocha>,       ["~> 0.9.8"])
    end
  else
    s.add_dependency(%q<activemodel>, ["~> 3.0"])
    s.add_dependency(%q<rake>,        "~> 12.3.3")
    s.add_dependency(%q<shoulda>,     ["~> 2.11.3"])
    s.add_dependency(%q<mocha>,       ["~> 0.9.8"])
  end
end

